import { SignedOut } from "@clerk/clerk-react";
import {
  SignInButton,
  SignedIn,
  UserButton,
  useAuth,
  useUser,
} from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const { user: clerkUser } = useUser();
  const { data: user } = api.user.getById.useQuery(clerkUser?.id ?? "", {
    enabled: !!clerkUser?.id,
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <div className="text-[hsl(280,100%,70%)]">T3</div> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div>
            <SignedIn>
              <div className="mb-4 flex items-center justify-center gap-2 text-white">
                <p>{"click me ->"}</p>
                <UserButton afterSignOutUrl="/" />
                <div>
                  <p className="text-2xl font-semibold">
                    {clerkUser?.fullName}
                  </p>
                  <p>{clerkUser?.username}</p>
                </div>
              </div>
              <p className="whitespace-pre-line text-center text-2xl text-white">
                {user
                  ? `Found you! Is this your ID?\n${user.id}`
                  : "Getting you from the database..."}
              </p>
            </SignedIn>
            <SignedOut>
              <SignInButton>
                <button className="rounded-xl bg-primary px-3 py-2 font-bold">
                  Sign In
                </button>
              </SignInButton>
            </SignedOut>
          </div>
        </div>
      </main>
    </>
  );
}
